### PR TITLE
Added h1_text

### PR DESCRIPTION
**Pull request by antoineeripret**
I added the h1-text variable  to retrieve the text from the first h1 tag in the rendered code.

### CODE REVIEW

**Comment by Tiggerito** [comment]
Does it work if there is no h1? We have to make sure our code causes no exceptions, because that will deny all others of the data. I'm thinking of wrapping anything non trivial in a try catch return error to reduce the chance of data loss. 

I'd personally check if any of the highest level hX tags had content that matched any of the title tags. And return a true/false on that. That would be a call from the authors. 

Getting the text like you do, does leaves our options open. The JS will be frozen soon, but with the text it returns we can analyse it later.

So now I own a forked repository that you have done a pull request on. And I can do the merge. What's the protocol, should I always merge to keep our local world in sync. And make sure I pull before the deadline?

**Comment by antoineeripret** [comment]
Hi, 

That's a good point, I don't know if we'd have a "null" value or an error. Let's wrap it in a try statement as you suggest. Do you want to take care of it or should I modify my pull request? 

Regarding the check, I'd rather do it in SQL using a CASE statement because we'd be able to finetune the comparison using LOWER() etc... **But as you prefer, to be honest, I'm more "fluent" in SQL than JS so my opinion may be skewed on that :)** 

Regarding the procedure, I'd do the following: 
- Merge my changes if OK 
- Commit your changes once you are done working locally. I'll be then able to sync again so we ensure we always work on up-to-date files. 

As we are working on different timezones, I think we'd have very few conflicts by working like this.

**Comment by Tiggerito** [comment]
That's good. I'm probably stronger in js than sql now.

This variation may fix the no h1 issue:

`document.querySelectorAll('h1')[0]?.textContent`

Notice the extra ?

It's a kind of short hand to say, if not undefined carry on. Instead of causing an exception when there is no h1, it will return undefined. The SQL side would then need to deal with that error situation.

Want to get uber new JS...

`document.querySelectorAll('h1')[0]?.textContent ?? 'h1 is missing'`

The ?? will return the value provided if it is not 'nullish', otherwise it will return the value after it. For our scenario maybe returning an empty string if nullish will make it simpler for the SQL to process?

This is modernish JS , but we know our code will be run using a recent version of Chrome.

**Comment by antoineeripret** [comment]
I just edited the pull request to include the last piece of code you sent. Thanks for the explanations, I really appreciate it :)

**Comment by Tiggerito** [comment]
Not sure if my example of 'h1 is missing' is a good example. What would you want your SQL to see if there is no h1? 

Typically you will be using a function to look at the data as a json object. So what is sent is what you have to deal with. 

As simple example of pulling out the almanac.js data is here:

https://github.com/HTTPArchive/almanac.httparchive.org/blob/seo-sql-2020/sql/2020/07_SEO/10_03_amphtml_rendered.sql

So you will still be dealing with JS, sorry. Plus SQL.

**Comment by antoineeripret** [comment]
Yes but the piece of JS above doesn't change that much between queries. We just have to update the following line according to what we actually want. 

`return !!almanac['**link-nodes**'].find(node => node.rel.toLowerCase() == '**amphtml**')`

AFAIK, Aleyda wants to compare <title> and H1 (which is why we extract h1 text value), hence this data will be useful only to see the % of cases where both contents are the same. Hence the 'h1 is missing' can be anything as we would exclude these cases from the % we would get using a WHERE clause in our SQL code. 

We should have an output table like: 

Situation | %
No H1 or no Title | XX%
Same H1 & Title | XX%
Different H1 & Title | XX%

**Comment by Tiggerito** [comment]
GitHub is confusing me now. When I made the fork from the original it also created a branch called patch-1, where I have been editing. This edit is in the master branch. So we are on different branches at the moment. Not sure how to do this?

I'll have a play.

**Comment by Tiggerito** [comment]
I think that worked. I pulled my patch to master and merged. I merged yours. So we're now all together. And it looks like I can still do a pull back to the original when we are ready to share :-)

**Comment by Tiggerito** [comment]
I've invited you as a collaborator. Hopefully that makes it easier to communicate and gives you more power.

**Comment by antoineeripret** [comment]
Perfect, I'll sync my local version with yours :)

**Comment by Tiggerito** [comment]
Hopefully this will make things smoother.

I'm currently refactoring the old SQL scripts so don't play there at the moment. I have a plan to reduce the number of scripts to make it easier to manage and save on big query costs.

**Comment by antoineeripret** [comment]
Ok, I'm adding the summary table for us in the Gdocs as mentioned in the Twitter conversation. Hopefully, it will help us get through the document easily when it comes to our part because right now the document is hard to scan :)

**Comment by Tiggerito** [comment]
Too right 🤯

**Comment by Tiggerito** [comment]
I've finished the SQL refactoring. The readme in the folder should give a bit of a clue.

I've also added some more to the almanac.js file to cover what's needed due to moving away from regex and body queries. 

There's a header property that kind of duplicates your h1_text. I'm trying to pull in as much data as possible so that we have the flexibility later to do more reports. 

I'll check your table tomorrow. Looks like it can tame the beast.

**Comment by antoineeripret** [comment]
@Tiggerito: Ok, I'll create all the tables in the Google Docs and have a look at what you did. I must that with all the commits and comments you added, I'm a bit lost but I will dive into it this afternoon as well :) 

Thanks !

**Comment by antoineeripret** [comment]
@Tiggerito : Leaving my comment here because I feel like the Google Docs is too full to add something else: 

1. All tables added. I still need to add the WPO part but apart of it, all metrics should be included
2. I see that obto asked you to pull your modified almanac.js you had been working hard on. Once reviewed by them, we should be able to divide SQL queries, shouldn't we? It is my understanding that you added a lot of custom metrics there and we'd have few JS (apart of the snippet added at the beginning of a lot of SQL queries) to add from now on. 

Thanks for everything (because let's be real, you are doing the heavy part) and talk to you tomorrow!

**Comment by Tiggerito** [comment]
Thanks for the heads up on the pull request. Just done it.

**Pull request merged**
